### ISSUE TITLE
Wie kann man Registrierungen deaktivieren

### ISSUE THREAD

**Issue by ghost** [lutana-de/viscacha#1]
Hallo Entwickler,
schön, dich auf GitHub mit dem offiziellen Viscacha-Repo anzutreffen. Ich habe das Forum erneut in der letzten Version aufgesetzt und würde gerne erfahren, wie die User-Registrierungen zu deaktivieren sind. Ich poste nämlich nur allein bei mir im Forum, da ich bereits mehrere öffentlich zugängliche Foren betreibe. 

Zudem wäre es mal cool zu erfahren, wie die Weiterentwicklung von Viscacha zur Zeit aussieht?!

Danke, Alexander

**Comment by m-mohr** [comment]
Hallo Alexander,

in der Administration unter "Viscacha Einstellungen" > "Registrierung" > "Sperrt die Registrierung" den Haken setzen und die Registrierung ist deaktiviert.

Ich entwickle die Software langsam weiter (siehe Entwicklungsbranch "Viscacha-0.9"), allerdings geht es auf Grund von recht eingeschränkter Freizeit recht langsam voran.

Viele Grüße

**Comment by ghost** [comment]
Hallo Matthias,
vielen Dank für den schnellen Tipp und ich werde deine Forumentwicklung gerne durch GitHub verfolgen. Da bin ich schon auf die nächste Version sehr gespannt und denke, ein Update wird dann auch gemacht.

Die Registrierungen habe ich nun auf inaktiv gesetzt. Dein Tipp half mir.
