### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function mysql_connect

### ISSUE THREAD

**Issue by ghost** [lutana-de/viscacha#4]
Hi,

wollte einen Bug melden, denn ich vermute, dass Viscacha, die alte Version, nicht mit MySQL 5.7 arbeiten kann. Die Fehlerausgabe geht so:

    Fatal error: Uncaught Error: Call to undefined function mysql_connect() in 
    xxxxxxxxxxxxx/viscacha.wpzweinull.ch/classes/database/mysql.inc.php:91 Stack trace: #0 
    xxxxxxxxxxxxxx/viscacha.wpzweinull.ch/classes/database/class.db_driver.php(202): DB->connect() #1 
    xxxxxxxxxxxxxxxxx/viscacha.wpzweinull.ch/classes/database/mysql.inc.php(147): DB_Driver->open() #2 
    xxxxxxxxxxxxxxxx/viscacha.wpzweinull.ch/classes/class.permissions.php(538): DB->query('SELECT sid 
    FROM...') #3 xxxxxxxxxxxxxxx/viscacha.wpzweinull.ch/classes/function.frontend_init.php(204): slog-
    >logged() #4 /xxxxxxxxxxxxxxxxx/viscacha.wpzweinull.ch/classes/function.viscacha_frontend.php(27): 
    require_once('/www/htdocs/w01...') #5 /xxxxxxxxxxxxxxxxxxx/viscacha.wpzweinull.ch/portal.php(33): 
    require_once('/www/htdocs/w01...') #6 /xxxxxxxxxxxxxxxxxxxx/viscacha.wpzweinull.ch/index.php(28): 
    include_once('/www/htdocs/w01...') #7 {main} thrown in 
    /xxxxxxxxxxxxxxxxxxx/viscacha.wpzweinull.ch/classes/database/mysql.inc.php on line 91

Ich habe zudem von PHP 7.0 auf PHP 5.5 umgeschaltet und wollte beobachten, was passiert. Der Fehler besteht noch.

Kannst du mir dazu etwas sagen?

Danke im Vorfeld.

**Comment by m-mohr** [comment]
Hallo,

bei dir ist die alte mysql-Erweiterung nicht verfügbar, daher musst du mysqli benutzen. Entweder bei der Installation entsprechend auswählen oder in der Konfigurationsdatei data/config.inc.php diese Zeile:
`$config['dbsystem'] = 'mysql';`
ändern in 
`$config['dbsystem'] = 'mysqli';`
Dann sollte es wieder funktionieren. Im Entwicklungsbranch 0.9 wird die mysql-Erweiterung nicht mehr unterstützt.
