### ISSUE TITLE
upgrading from 8.1.1 to 8.1.2

### ISSUE THREAD

**Issue by ibertrix** [lutana-de/viscacha#5]
Dear team,

  I have an installation of Viscacha 8.1.1. I see that 8.1.3 version supports PHP 7 and beyond MySQL 5.5.

 I have searched and it seems that I need to upgrade first to 8.1.2. However I can´t find the update package for 8.1.2, only for 8.1.3.

  Can you provide an URL to download the update package?

  The instructions to upgrade are not clear. Do I have to override the install folder? and after what should I do?

  Thanks!

**Comment by m-mohr** [comment]
Hi,

download the version tagged as release 0.8.1.2 (see https://github.com/lutana-de/viscacha/releases/tag/0.8.1.2 ) and follow the instructions in the README.md file.
